### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dalb8** [wisedog/Whoochoo#2]
Would you like to cover the code with a free software license, such as those found at http://choosealicense.com. I'd like to propose the app for inclusion in the  market at f-droid.org, which only has FOSS apps.

**Comment by wisedog** [comment]
This project will be covered by Apache license. Thx

**Comment by dalb8** [comment]
Can you push a tag for 1.1.1, the current version on Google Play, please

**Comment by dalb8** [comment]
On second thoughts, I'd rather not have that version with Admob. I'll wait for the next version

**Comment by wisedog** [comment]
I will push release branch which has tag 1.1.1. 
And now I remove Admob on develop branch. Thanks

**Comment by dalb8** [comment]
I just see the tag for 1.2.0. I completed the recipe, you can send it to them if you like:

```
Categories:Office
License:Apache2
Web Site:https://peashellapp.blogspot.kr
Source Code:https://github.com/wisedog/Whoochoo
Issue Tracker:https://bitbucket.org/wisedognet/whooing-for-android/issues

Auto Name:WhooChoo
Summary:Client for whooing.com
Description:
"Whoochoo" is a client for the Korea-based website whooing.com, for double-entry 
bookkeeping. 
You can manage your expenses, account, income, cash flow by this application.
.

Repo Type:git
Repo:https://github.com/wisedog/Whoochoo.git

Build:1.2.0,120
    commit=v1.2.0
    srclibs=1:ActionBarSherlock@4.4.0
    prebuild=mv libs/android-support-v4.jar $$ActionBarSherlock$$/libs/

Auto Update Mode:None
Update Check Mode:Tags
Current Version:1.2.0
Current Version Code:120

```

**Comment by wisedog** [comment]
WebSite : http://story.wisedog.net/category/my_programming_stuff
Issue Tracker : https://github.com/wisedog/Whoochoo/issues
